<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>ego.html</string>
	</array>
	<key>name</key>
	<string>Ego (HTML)</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>text.html.basic</string>
		</dict>
		<dict>
			<key>include</key>
			<string>source.ego</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>text.html.egohtml</string>
	<key>uuid</key>
	<string>EFACEB56-5A9D-439D-8B6A-4B22647773B4</string>
</dict>
</plist>
