<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>ego.html</string>
	</array>
	<key>name</key>
	<string>Ego</string>
	<key>patterns</key>
	<array>
		<!--
		<dict>
			<key>begin</key>
			<string>(\&lt;[a-zA-Z0-9]+)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.begin.html.ego.html</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>handle ego.html inside html</string>
			<key>end</key>
			<string>(\&lt;)?(/)([a-zA-Z0-9\-]+)?(\&gt;)</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.end.html.ego.html</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.end.slash.html.ego.html</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>entity.name.end.html.ego.html</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>entity.name.end.html.ego.html</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>comment</key>
					<string>attribute</string>
					<key>match</key>
					<string>([a-zA-Z0-9\-]+\=)(?=[\&apos;\&quot;\@])</string>
					<key>name</key>
					<string>entity.name.attribute.ego.html</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>(?&lt;=\=)(\&apos;)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>string.quoted.single.ego.html</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>single quotes</string>
					<key>end</key>
					<string>(\&apos;)</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>string.quoted.single.ego.html</string>
						</dict>
					</dict>
					<key>name</key>
					<string>text.basic.ego.html</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>$self</string>
						</dict>
						<dict>
							<key>match</key>
							<string>.</string>
							<key>name</key>
							<string>string.quoted.single.ego.html</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(?&lt;=\=)(\&quot;)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>string.quoted.double.ego.html</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>double quotes</string>
					<key>end</key>
					<string>(\&quot;)</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>string.quoted.double.ego.html</string>
						</dict>
					</dict>
					<key>name</key>
					<string>text.basic.ego.html</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>$self</string>
						</dict>
						<dict>
							<key>match</key>
							<string>.</string>
							<key>name</key>
							<string>string.quoted.double.ego.html</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(\&gt;)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.name.begin.closing.ego.html</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>innerHTML</string>
					<key>end</key>
					<string>(\&lt;[a-zA-Z0-9]*)</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.name.end.opeing.ego.html</string>
						</dict>
					</dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>$self</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>comment</key>
					<string>swallow quotes</string>
					<key>match</key>
					<string>\&apos;|\&quot;</string>
				</dict>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
				<dict>
					<key>include</key>
					<string>text.html.basic</string>
				</dict>
				<dict>
					<key>include</key>
					<string>source.go</string>
				</dict>
			</array>
		</dict>
		-->
		<dict>
			<key>begin</key>
			<string>(@\{)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.class.ego.html</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>code block</string>
			<key>contentName</key>
			<string>source.go</string>
			<key>end</key>
			<string>^\}$</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>support.class.ego.html</string>
				</dict>
			</dict>
			<key>name</key>
			<string>source.go</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#block</string>
				</dict>
				<dict>
					<key>include</key>
					<string>source.go</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(@)((if|for|switch|section)? )([^\{\n]+)(\{)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.class.ego.html</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>keyword.control.go</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>source.go</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>support.class.ego.html</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>transition brace</string>
			<key>end</key>
			<string>\}</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>support.class.ego.html</string>
				</dict>
			</dict>
			<key>name</key>
			<string>source.brace.go</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
				<dict>
					<key>include</key>
					<string>source.go</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(@\*)</string>
			<key>comment</key>
			<string>Multi-line Comments</string>
			<key>end</key>
			<string>(\*@)</string>
			<key>name</key>
			<string>comment.line.ego.html</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Escaped transition character</string>
			<key>match</key>
			<string>@@</string>
			<key>name</key>
			<string>string.regexp</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(@\()</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.class.ego.html</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>\@(variable expression)</string>
			<key>end</key>
			<string>(\))</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.class.ego.html</string>
				</dict>
			</dict>
			<key>name</key>
			<string>source.go</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#function</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(\@)([a-zA-Z\.]+)(\()</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.class.ego.html</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>support.class.ego.html</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>support.class.ego.html</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>\@module.func(....)</string>
			<key>end</key>
			<string>(\))</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.class.ego.html</string>
				</dict>
			</dict>
			<key>name</key>
			<string>module.func</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#function</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comma</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#string</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(\@)([a-zA-Z\.]+)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.class.ego.html</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>support.class.ego.html</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>\@variable</string>
			<key>end</key>
			<string>(\b)</string>
			<key>name</key>
			<string>source.go</string>
		</dict>
		<dict>
			<key>include</key>
			<string>text.html.basic</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>block</key>
		<dict>
			<key>begin</key>
			<string>\{</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.bracket.begin</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>code block</string>
			<key>end</key>
			<string>\}</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.bracket.end</string>
				</dict>
			</dict>
			<key>name</key>
			<string>source.block.go</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
				<dict>
					<key>include</key>
					<string>source.go</string>
				</dict>
			</array>
		</dict>
		<key>comma</key>
		<dict>
			<key>match</key>
			<string>([, ]+)</string>
			<key>name</key>
			<string>punctuation.definition.comma.go</string>
		</dict>
		<key>function</key>
		<dict>
			<key>begin</key>
			<string>([a-zA-Z]+)(\()</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.function.go</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(\))</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#function</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#method</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#variable</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#string</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comma</string>
				</dict>
			</array>
		</dict>
		<key>method</key>
		<dict>
			<key>begin</key>
			<string>([a-zA-Z]+).([a-zA-Z]+)(\()</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.class.ego.html</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>support.function.go</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(\))</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.class.ego.html</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#function</string>
				</dict>
			</array>
		</dict>
		<key>string</key>
		<dict>
			<key>begin</key>
			<string>(\&quot;)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>string.quoted.double.ego.html</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(\&quot;)</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>string.quoted.double.ego.html</string>
				</dict>
			</dict>
			<key>name</key>
			<string>text.basic.ego.html</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>.</string>
					<key>name</key>
					<string>string.quoted.double.ego.html</string>
				</dict>
			</array>
		</dict>
		<key>variable</key>
		<dict>
			<key>match</key>
			<string>([a-zA-Z]+)</string>
			<key>name</key>
			<string>variable.other.go</string>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>text.html.ego</string>
	<key>uuid</key>
	<string>2C9B459B-7035-4C8B-BDBA-D01CC3A03EA0</string>
</dict>
</plist>
